name: asatic
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  app_settings: ^4.1.8
  isolated_download_manager_flutter: ^1.0.2
  badges: ^2.0.3
  blurry_modal_progress_hud: ^1.0.3
  circular: ^0.0.5
  connectivity_plus: ^2.3.6+1
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  dropdown_button2: ^1.8.9
  equatable: ^2.0.5
  flash: ^2.0.3+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_folding_card: ^1.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^6.0.0
  flutter_socket_client:
    path: ./flutter_socket_channel
  flutter_spinner_picker: ^0.0.7
  flutter_svg: ^1.1.4
  flutter_switch: ^0.3.2
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  injectable: ^1.5.3
  internet_connection_checker: ^0.0.1+4
  jwt_decode: ^0.3.1
  logger: ^1.1.0
  lottie: ^1.4.2
  ndialog: ^4.1.1+1
  numeric_keyboard: ^1.1.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  persian_datetime_picker: ^2.5.0
  pin_code_fields: ^7.4.0
  salomon_bottom_bar: ^3.3.1
  scroll_snap_list: ^0.9.1
  step_progress_indicator: ^1.0.2
  syncfusion_flutter_gauges: ^20.2.46
  time_picker_sheet: ^0.0.2+1
  web_socket_channel: ^2.2.0
  url_launcher: ^6.1.7
  wifi_iot: ^0.3.18
  wifi_scan: ^0.4.0+1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_asatic_icon.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/svg/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IRANSans
      fonts:
        - asset: assets/fonts/iransans/IRANSansUltraLight.ttf
        - asset: assets/fonts/iransans/IRANSansLight.ttf
        - asset: assets/fonts/iransans/IRANSansMedium.ttf
        - asset: assets/fonts/iransans/IRANSansBold.ttf
        - asset: assets/fonts/iransans/IRANSans.ttf
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
